In [7]:
import numpy as np


In [227]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


How many negative numbers are there?

In [74]:
len(a[a < 0])

4

How many positive numbers are there?

In [73]:
len(a[a > 0])

5

How many even positive numbers are there?

In [82]:
ep = (a[a > 0])
ep

array([ 4, 10, 12, 23,  3])

In [84]:
len(ep[ep % 2 == 0])


3

If you were to add 3 to each data point, how many positive numbers would there be?

In [77]:
plus_three = a + 3

In [78]:
len(plus_three[plus_three > 0])

10

If you squared each number, what would the new mean and standard deviation be?

In [90]:
sqrd = a ** 2
sqrd

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [92]:
sqrd.mean()

74.0

In [89]:
sqrd.std()

144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [93]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [ ]:
Calculate the z-score for each data point. Recall that the z-score is given by:

In [94]:
(a - a.mean())/a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions. Use python's built in functionality/operators to determine the following:

In [231]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [232]:
sum(a)

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [233]:
min(a)

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [234]:
max(a)

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [108]:
mean_of_a = a.mean()
mean_of_a

5.5

In [235]:
sum(a)/ len(a)

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [260]:
product_of_a = 1

for i in a:
    product_of_a *= i
    
product_of_a

3628800

In [ ]:
Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [261]:
squares_of_a = []

for i in a:
    squares_of_a.append(i**2)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [262]:
odds_in_a = []

for i in a:
    if i % 2 == 1:
        odds_in_a.append(i)
        
odds_in_a

[1, 3, 5, 7, 9]

Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [263]:
evens_in_a = []

for i in a:
    if i % 2 == 0:
        evens_in_a.append(i)
    
evens_in_a

[2, 4, 6, 8, 10]

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [129]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]])

In [137]:
print(b.sum())
print(b.min())
print(b.max())
print(b.mean())
print(b.prod())
print(b ** 2)

33
3
8
5.5
20160
[[ 9 16 25]
 [36 49 64]]


Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [158]:
sum_of_b = b.sum()
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [159]:
min_of_b = b.min()
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


In [156]:
max_of_b = b.max
max_of_b

8

Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [160]:
mean_of_b = b.mean()
mean_of_b

5.5

Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [162]:
product_of_b = b.prod()
product_of_b

20160

Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [164]:
squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [166]:
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)


In [167]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

In [168]:
b.shape

(2, 3)

Exercise 10 - transpose the array b.

In [170]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [177]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [178]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [180]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

Exercise 1 - Find the min, max, sum, and product of c.

In [183]:
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


Exercise 2 - Determine the standard deviation of c.

In [184]:
c.std()

2.581988897471611

In [ ]:
Exercise 3 - Determine the variance of c.

In [185]:
c.var()

6.666666666666667

Exercise 4 - Print out the shape of the array c

In [186]:
c.shape

(3, 3)

Exercise 5 - Transpose c and print out transposed result.

In [187]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c. 

In [239]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [213]:
tposed = c * c.transpose()
tposed.sum()

261

In [ ]:
Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [214]:
tprod = c * c.transpose()
tprod.prod()

131681894400

In [241]:
(c * c.transpose()).prod()

131681894400

In [219]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]])

Exercise 1 - Find the sine of all the numbers in d

In [242]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [254]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [253]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [246]:
d[d<0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [245]:
d[d>0] 

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [251]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [244]:
len(np.unique(d))

11

Exercise 8 - Print out the shape of d.

In [247]:
d.shape

(3, 6)

Exercise 9 - Transpose and then print out the shape of d.

In [248]:
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

Exercise 10 - Reshape d into an array of 9 x 2

In [250]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])